spring:
#  mvc:
#    view:
#      prefix: /jsp/
#      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties.hibernate:
      dialect:
      default_schema: public
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false
  messages:
    basename: translations